import { PoopAnalysisResult } from "../types";

// 현재 시간 포맷팅
const getCurrentTime = () => {
  const now = new Date();
  return now.toLocaleString('ko-KR', { 
    month: 'long', 
    day: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit' 
  });
};

// 랜덤 결과 데이터 (엄마 친화적 UI)
const mockResults: PoopAnalysisResult[] = [
  {
    status: 'normal',
    statusLabel: '정상',
    description: '건강한 상태의 대변입니다.',
    friendlyHeadline: '오늘 우리 아기 장이 아주 튼튼해요!',
    friendlyEmoji: '☀️',
    color: '황금색',
    colorHex: '#DAA520',
    colorFriendly: '황금변',
    consistency: '부드러움',
    frequencyToday: 3,
    poopShape: '🍌 바나나',
    poopShapeDesc: '아주 건강해요',
    amount: '보통',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: false,
    hydration: '양호',
    bristolType: 4,
    hydrationAdvice: '수분 섭취 충분해요! 지금처럼 유지해 주세요 💧',
    careAdvice: ['현재 수유 패턴 그대로 유지하세요', '아기와 눈 맞추며 수유하면 더 좋아요'],
    hospitalAdvice: null,
    insight: '모유 수유 아기에게 흔히 보이는 건강한 대변이에요. 엄마 젖이 아기에게 딱 맞고 있다는 증거예요!',
    recommendations: ['현재 수유 패턴 유지', '충분한 수분 섭취'],
    warningSigns: [],
    analysisTime: getCurrentTime(),
    confidenceScore: 94
  },
  {
    status: 'normal',
    statusLabel: '정상',
    description: '정상적인 대변 색상과 농도입니다.',
    friendlyHeadline: '소화가 아주 잘 되고 있어요!',
    friendlyEmoji: '✨',
    color: '겨자색',
    colorHex: '#E1AD01',
    colorFriendly: '겨자변',
    consistency: '크림형',
    frequencyToday: 4,
    poopShape: '🍌 바나나',
    poopShapeDesc: '건강해요',
    amount: '보통',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: false,
    hydration: '양호',
    bristolType: 5,
    hydrationAdvice: '수분 상태 좋아요! 계속 잘 챙겨주세요 👍',
    careAdvice: ['규칙적인 수유 시간을 유지해 주세요', '배변 일지를 기록하면 패턴을 파악하기 좋아요'],
    hospitalAdvice: null,
    insight: '겨자색 크림형 변은 모유 수유 아기의 전형적인 건강 변이에요. 아기 장이 튼튼하다는 신호!',
    recommendations: ['규칙적인 수유', '배변 일지 작성'],
    warningSigns: [],
    analysisTime: getCurrentTime(),
    confidenceScore: 91
  },
  {
    status: 'normal',
    statusLabel: '정상',
    description: '녹색빛이 약간 있지만 정상 범위입니다.',
    friendlyHeadline: '녹변이지만 걱정 마세요, 정상이에요!',
    friendlyEmoji: '🌿',
    color: '녹황색',
    colorHex: '#9ACD32',
    colorFriendly: '녹변 (정상)',
    consistency: '보통',
    frequencyToday: 2,
    poopShape: '🍌 바나나',
    poopShapeDesc: '건강해요',
    amount: '보통',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: false,
    hydration: '양호',
    bristolType: 4,
    hydrationAdvice: '수분 충분해요 💧',
    careAdvice: ['전유(묽은 젖)를 많이 먹으면 녹색이 될 수 있어요', '한쪽 젖을 충분히 먹인 후 바꿔주세요'],
    hospitalAdvice: null,
    insight: '녹색빛은 담즙 색소 때문이고 정상이에요. 전유를 많이 먹거나 장 통과가 빠르면 나타나요.',
    recommendations: ['수유 시간 충분히', '한쪽 젖 완전히 비우기'],
    warningSigns: [],
    analysisTime: getCurrentTime(),
    confidenceScore: 88
  },
  {
    status: 'caution',
    statusLabel: '관찰 필요',
    description: '약간 묽은 편이니 관찰이 필요해요.',
    friendlyHeadline: '장이 조금 예민한 것 같아요',
    friendlyEmoji: '💧',
    color: '노란색',
    colorHex: '#EAB308',
    colorFriendly: '노란 물변',
    consistency: '묽음',
    frequencyToday: 6,
    poopShape: '🍚 묽은 죽',
    poopShapeDesc: '설사 기운이 있어요',
    amount: '많음',
    hasMucus: true,
    hasBlood: false,
    hasUndigested: false,
    hydration: '주의',
    bristolType: 6,
    hydrationAdvice: '수분이 빠져나가고 있어요! 평소보다 수유를 자주, 조금씩 해주세요 🚰',
    careAdvice: ['모유/분유를 조금씩 자주 먹여주세요', '전해질 용액(페디라이트)을 고려해 보세요', '기저귀 발진 예방 크림을 발라주세요'],
    hospitalAdvice: '탈수 증상(눈물 없이 울기, 소변 줄어듦, 입술 마름)이 보이면 소아과에 가세요',
    insight: '점액이 조금 보이고 배변 횟수가 많아요. 장이 예민해진 상태니까 수분 섭취에 신경 써주세요!',
    recommendations: ['수분 보충', '컨디션 관찰'],
    warningSigns: ['점액 소량 발견'],
    analysisTime: getCurrentTime(),
    confidenceScore: 85
  },
  {
    status: 'caution',
    statusLabel: '관찰 필요',
    description: '단단한 편이니 수분 섭취를 늘려주세요.',
    friendlyHeadline: '변비 기운이 있어요, 물을 더 챙겨주세요!',
    friendlyEmoji: '🐰',
    color: '진갈색',
    colorHex: '#8B4513',
    colorFriendly: '갈색변',
    consistency: '딱딱함',
    frequencyToday: 1,
    poopShape: '🐰 토끼똥',
    poopShapeDesc: '변비 기운이 있어요',
    amount: '소량',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: true,
    hydration: '보통',
    bristolType: 2,
    hydrationAdvice: '물을 한 컵 더 챙겨주세요! 수분이 부족해 보여요 💧',
    careAdvice: ['배 마사지를 시계 방향으로 3분간 해주세요 🔄', '다리를 자전거 타듯 움직여 주세요', '이유식 중이라면 수분기 있는 음식을 추가해 보세요'],
    hospitalAdvice: '3일 이상 변을 못 보거나 배가 많이 빵빵하면 소아과에 가세요',
    insight: '변이 딱딱하고 토끼똥처럼 작게 나왔어요. 수분 섭취를 늘리고 배 마사지를 해주면 좋아질 거예요!',
    recommendations: ['물 섭취량 늘리기', '배 마사지'],
    warningSigns: ['변비 징후'],
    analysisTime: getCurrentTime(),
    confidenceScore: 82
  },
  {
    status: 'normal',
    statusLabel: '정상',
    description: '이유식 아기의 정상적인 대변이에요.',
    friendlyHeadline: '이유식 잘 소화하고 있어요!',
    friendlyEmoji: '🥄',
    color: '연갈색',
    colorHex: '#D2691E',
    colorFriendly: '갈색변',
    consistency: '성형됨',
    frequencyToday: 2,
    poopShape: '🍌 바나나',
    poopShapeDesc: '건강해요',
    amount: '보통',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: true,
    hydration: '양호',
    bristolType: 4,
    hydrationAdvice: '수분 상태 좋아요! 💧',
    careAdvice: ['다양한 이유식을 시도해 보세요', '새 음식은 3일 간격으로 한 가지씩 추가해요', '음식 조각이 보이는 건 정상이에요!'],
    hospitalAdvice: null,
    insight: '이유식 시작 후 변 색과 질감이 변하는 건 자연스러워요. 음식 조각이 보이는 것도 6-12개월 아기에겐 흔한 일이에요.',
    recommendations: ['다양한 이유식 시도', '알레르기 관찰'],
    warningSigns: [],
    analysisTime: getCurrentTime(),
    confidenceScore: 90
  },
  {
    status: 'normal',
    statusLabel: '정상',
    description: '분유 수유 아기의 건강한 대변이에요.',
    friendlyHeadline: '분유가 아기에게 잘 맞아요!',
    friendlyEmoji: '🍼',
    color: '황갈색',
    colorHex: '#C4A35A',
    colorFriendly: '황갈변',
    consistency: '페이스트형',
    frequencyToday: 2,
    poopShape: '🍌 바나나',
    poopShapeDesc: '건강해요',
    amount: '보통',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: false,
    hydration: '양호',
    bristolType: 4,
    hydrationAdvice: '수분 섭취 좋아요! 💧',
    careAdvice: ['현재 분유를 계속 유지해 주세요', '적정 온도(체온 정도)로 수유해 주세요', '수유 후 트림을 잘 시켜주세요'],
    hospitalAdvice: null,
    insight: '분유 수유 아기의 전형적인 건강 변이에요. 황갈색 페이스트 형태는 분유가 잘 소화되고 있다는 신호!',
    recommendations: ['현재 분유 유지', '트림 잘 시키기'],
    warningSigns: [],
    analysisTime: getCurrentTime(),
    confidenceScore: 92
  },
  {
    status: 'caution',
    statusLabel: '관찰 필요',
    description: '거품이 섞인 변이 관찰됩니다.',
    friendlyHeadline: '거품변이에요, 수유 방법을 확인해 보세요',
    friendlyEmoji: '🫧',
    color: '연노랑',
    colorHex: '#F0E68C',
    colorFriendly: '거품변',
    consistency: '거품형',
    frequencyToday: 5,
    poopShape: '🫧 거품',
    poopShapeDesc: '장이 예민해요',
    amount: '많음',
    hasMucus: false,
    hasBlood: false,
    hasUndigested: false,
    hydration: '보통',
    bristolType: 6,
    hydrationAdvice: '수분 상태는 괜찮아요 💧',
    careAdvice: ['한쪽 젖을 충분히 비운 후 다른 쪽으로 바꿔주세요', '전유-후유 불균형일 수 있어요', '수유 자세를 확인해 보세요'],
    hospitalAdvice: '거품변이 계속되면 유당 불내증 검사를 위해 소아과 상담을 권해요',
    insight: '거품이 섞인 변은 전유-후유 불균형이나 유당 불내증 신호일 수 있어요. 한쪽 젖을 충분히 먹인 후 바꿔보세요.',
    recommendations: ['한쪽 젖 충분히 수유', '소아과 상담 고려'],
    warningSigns: ['거품 변'],
    analysisTime: getCurrentTime(),
    confidenceScore: 78
  }
];

// 기저귀가 아닌 경우 결과
const invalidResult: PoopAnalysisResult = {
  status: 'invalid',
  statusLabel: '인식 불가',
  description: '기저귀 사진이 아닙니다.',
  friendlyHeadline: '기저귀 사진이 필요해요',
  friendlyEmoji: '📷',
  color: '-',
  colorHex: '#CCCCCC',
  colorFriendly: '-',
  consistency: '-',
  frequencyToday: 0,
  poopShape: '-',
  poopShapeDesc: '-',
  amount: '보통',
  hasMucus: false,
  hasBlood: false,
  hasUndigested: false,
  hydration: '보통',
  bristolType: 0,
  hydrationAdvice: '-',
  careAdvice: [],
  hospitalAdvice: null,
  insight: '기저귀 사진을 업로드해 주세요. 배변이 보이는 기저귀를 선명하게 촬영해 주시면 더 정확한 분석이 가능합니다.',
  recommendations: ['기저귀 사진 다시 촬영', '밝은 곳에서 촬영', '배변 부분이 잘 보이게 촬영'],
  warningSigns: [],
  analysisTime: getCurrentTime(),
  confidenceScore: 0
};

export async function analyzePoopImage(base64Image: string): Promise<PoopAnalysisResult> {
  // 분석하는 것처럼 1~2초 딜레이
  await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 1000));
  
  // 15% 확률로 "기저귀가 아님" 결과 반환 (데모용)
  if (Math.random() < 0.15) {
    return { ...invalidResult, analysisTime: getCurrentTime() };
  }
  
  // 랜덤 결과 반환 (시간 업데이트)
  const randomIndex = Math.floor(Math.random() * mockResults.length);
  return { ...mockResults[randomIndex], analysisTime: getCurrentTime() };
}
